### ISSUE TITLE
Segmentation Fault on drawBorder

### ISSUE THREAD

**Issue by sqd** [jmillikin/haskell-ncurses#2]
minimal buggy code: https://drive.google.com/file/d/0B7CswEyboSTzV3BiWkczVEpKclE/view?usp=sharing
coredump: https://drive.google.com/file/d/0B7CswEyboSTzR2pFRjBfZDBIYkk/view?usp=sharing

**Comment by jmillikin** [comment]
What version of c2hs are you building with? Version 0.25.2 is known to generate incorrect code (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=786727#28).

Try building with an older c2hs (e.g. 0.18.2) and see if it fixes the crash.

I have an old TODO to track down exactly what versions of c2hs are affected and handle them with ifdefs. Recently I've not had much time for Haskell package maintenance, but I'll try to set aside some for this bug since it's affecting multiple people.

**Comment by jmillikin** [comment]
Could you update to commit b44ae6e41bab47442d6fad8871d3f4e6e705aa40 or later to see if it fixes the crash for you? I replaced the c2hs-based code with a C shim function, so that code path should not be broken by c2hs's behavior any more.

**Comment by sqd** [comment]
Updating to the commit solves the problem, thx :)
I was using

```
$ c2hs --version
C->Haskell Compiler, version 0.26.1 Budburst, 4 April 2015
  build platform is "i386-linux" <1, True, True, 1>
```

**Comment by sqd** [comment]
Plus, using c2hs 0.18.2 also solves the problem

**Comment by jmillikin** [comment]
Version 0.2.12 has been pushed to Hackage with the fix.
